#ScenicView properties
#Sun Sep 27 00:49:41 MSK 2026
autoRefreshStyleSheets=false
automaticScenegraphStructureRefreshing=true
collapseContainerControls=false
collapseControls=true
ignoreMouseTransparentNodes=true
registerShortcuts=true
showBaseline=false
showBounds=true
showCSSProperties=false
showDefaultProperties=true
showFilteredNodesInTree=true
showInvisibleNodes=false
showNodesIdInTree=false
showSearchBar=true
splitPaneDividerPosition=0.308125
stageHeight=800.0
stageWidth=800.0
